name: flutter_application_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  appwrite: ^11.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  firebase_messaging: ^14.7.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  fluttertoast: ^8.2.4
  get: 4.6.6
  http: ^0.13.3
  image_picker: ^0.8.4+2
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
