// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZsRgYt4VfGvsa_whEFL27Hbf7lF0GnHc',
    appId: '1:951266128983:web:bad478718131d3e34c9f12',
    messagingSenderId: '951266128983',
    projectId: 'restaurant-app-5c0a9',
    authDomain: 'restaurant-app-5c0a9.firebaseapp.com',
    storageBucket: 'restaurant-app-5c0a9.appspot.com',
    measurementId: 'G-0P3GQRGNDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOeuuQQ4S521GwVRh-FP_e_MLpzFqd49M',
    appId: '1:951266128983:android:9a8445f36cca21244c9f12',
    messagingSenderId: '951266128983',
    projectId: 'restaurant-app-5c0a9',
    storageBucket: 'restaurant-app-5c0a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-uah43lDRyvXS8NfKppNBy7RzRQfJTQo',
    appId: '1:951266128983:ios:eb50f2b4bb88fd594c9f12',
    messagingSenderId: '951266128983',
    projectId: 'restaurant-app-5c0a9',
    storageBucket: 'restaurant-app-5c0a9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-uah43lDRyvXS8NfKppNBy7RzRQfJTQo',
    appId: '1:951266128983:ios:f27a5a3741289d844c9f12',
    messagingSenderId: '951266128983',
    projectId: 'restaurant-app-5c0a9',
    storageBucket: 'restaurant-app-5c0a9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
